// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC_hCACsCLWt1YJQXA3s5Dr9VvyN8x_qU',
    appId: '1:696301183996:web:3cfb08a5eeec8c039cc879',
    messagingSenderId: '696301183996',
    projectId: 'campus-lost-found-app-nsbm',
    authDomain: 'campus-lost-found-app-nsbm.firebaseapp.com',
    storageBucket: 'campus-lost-found-app-nsbm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ur8lrH0j2bdtGm-o_jCvDRXvlCPRxbQ',
    appId: '1:696301183996:android:390434d0f9f500df9cc879',
    messagingSenderId: '696301183996',
    projectId: 'campus-lost-found-app-nsbm',
    storageBucket: 'campus-lost-found-app-nsbm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhkJydV-28y_gq6wOn9bIalajHVkhpKpY',
    appId: '1:696301183996:ios:5bff7dc37470525e9cc879',
    messagingSenderId: '696301183996',
    projectId: 'campus-lost-found-app-nsbm',
    storageBucket: 'campus-lost-found-app-nsbm.firebasestorage.app',
    iosBundleId: 'com.example.campusLostFoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhkJydV-28y_gq6wOn9bIalajHVkhpKpY',
    appId: '1:696301183996:ios:5bff7dc37470525e9cc879',
    messagingSenderId: '696301183996',
    projectId: 'campus-lost-found-app-nsbm',
    storageBucket: 'campus-lost-found-app-nsbm.firebasestorage.app',
    iosBundleId: 'com.example.campusLostFoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC_hCACsCLWt1YJQXA3s5Dr9VvyN8x_qU',
    appId: '1:696301183996:web:bb21336bf72cb9c69cc879',
    messagingSenderId: '696301183996',
    projectId: 'campus-lost-found-app-nsbm',
    authDomain: 'campus-lost-found-app-nsbm.firebaseapp.com',
    storageBucket: 'campus-lost-found-app-nsbm.firebasestorage.app',
  );
}
